"use client";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./Components/Nav/page";
import { Image } from "react-bootstrap";
import { usePathname } from "next/navigation";
const inter = Inter({ subsets: ["latin"] });


// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };
<link
  href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
  rel="stylesheet"
  integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH"
  crossorigin="anonymous"
></link>;

export default function RootLayout({ children }) {
  const pathname = usePathname();
  const showHeader = !pathname.startsWith("/dashboard");
  return (
    <html lang="en">
      <body className={inter.className}>
        {showHeader && <Header />}
        {children}
      </body>
    </html>
  );
}
